### ISSUE TITLE
好像接口被封了

### ISSUE THREAD

**Issue by gallexy** [goodpaperman/jinjing365#1]
该网站已接入<span style='font-size: 14px;color: #006cb8;'><strong>电信云堤&bull;网站安全防护服务</strong></span>，由于您使用的请求方法存在潜在安全风险，被云堤网站安全防护拦截。如果您有任何疑问或者认为这是一个误报，请您通过以下方式联系<span style='font-size: 14px;color: #006cb8;'><strong>7X24</strong></span>小时客服： </p> <p style='line-height: 28px;'> 紧急处理电话：<span style='font-size: 14px;color: #006cb8;'><strong>4009-259-120</strong></span> 语音提示后，请按“<span style='font-size: 14px;color: #006cb8;'><strong>2</strong></span>”转接人工服务 <br> 在线客服QQ：<span style='font-size: 14px;color: #006cb8;'><strong>454377235</strong></span> </p> <p> <span style='font-size: 14px;color: #006cb8;'><strong id='alter_submit'>在线提交（30分钟后请您刷新页面重试）：</strong></span> </p> </li> <li style='margin-top:20px; text-align: center; font-size: 14px;'> <input id='mobile' type='text' placeholder='请输入您的联系方式' required='' style='border-color: #fff; background: #f6f6f6; padding-left: 5px; border: 1px solid #ddd; border-radius: 5; height: 2.0rem; width: 99%; margin: 0 0 20px 0; box-shadow: none; box-sizing: border-box; transition: all .3s; padding: 5px; '> <input id='content' type='text' placeholder='请输入您的申诉内容' required='' style='border-color: #fff; background: #f6f6f6; padding-left: 5px; border: 1px solid #ddd; border-radius: 5; height: 5.0rem; width: 99%; margin: 0 0 20px 0; box-shadow: none; box-sizing: border-box; transition: all .3s; padding: 5px; '> <button style='width: 99%; height: 32px; margin: auto; text-align: center; color: white; border: 0px; background-color: #4e6ef2; border-radius: 5px; ' onclick='onSend()'>问题反馈</button> <hr style='margin-top:60px;'><center>chn-bj-yd/1.0.0</center> </li> </ul> </div> </body> </html>”“”

**Comment by gallexy** [comment]
好像是客户端需要用国内IP，用外网IP会失败

**Comment by goodpaperman** [comment]
刚看了下，后台脚本确实报错了，提示令牌失效，更新了一下 authentication 字段，又能跑了

**Comment by goodpaperman** [comment]
> 好像是客户端需要用国内IP，用外网IP会失败

那没辙儿了~
